### ISSUE TITLE
AttributeError: module 'io' has no attribute 'text_encoding'

### ISSUE THREAD

**Issue by wimglenn** [cielavenir/zipfile39#4]
```
~/opt/miniconda3/envs/jd37/lib/python3.7/site-packages/zipfile39/zipfile39.py in read_text(self, *args, **kwargs)
   2646     def read_text(self, *args, **kwargs):
   2647         if sys.version_info[0]>=3:
-> 2648             kwargs["encoding"] = io.text_encoding(kwargs.get("encoding"))
   2649         with self.open('r', *args, **kwargs) as strm:
   2650             return strm.read()

AttributeError: module 'io' has no attribute 'text_encoding'
```

[`io.text_encoding` is shown as _New in version 3.10_ in the docs](https://docs.python.org/3/library/io.html#io.text_encoding), so I'm not sure how the backport is supposed to use this. What am I missing?

Steps to reproduce:

```
from zipfile39 import Path as zfpath
p = zfpath("six-1.16.0-py2.py3-none-any.whl", "six-1.16.0.dist-info/METADATA")
p.read_text()
```

**Comment by cielavenir** [comment]
Can you test https://github.com/cielavenir/zipfile39/pull/5 change? Meanwhile I will prepare pytest

**Comment by wimglenn** [comment]
With that I get:

```
>>> p.read_text()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wim/opt/miniconda3/envs/jd37/lib/python3.7/site-packages/zipfile39/zipfile39.py", line 2656, in read_text
    with self.open('r', *args, **kwargs) as strm:
  File "/Users/wim/opt/miniconda3/envs/jd37/lib/python3.7/site-packages/zipfile39/zipfile39.py", line 2643, in open
    return io.TextIOWrapper(stream, *args, **kwargs)
LookupError: unknown encoding: locale
```

**Comment by cielavenir** [comment]
I was able to prepare pytest and fix the issue
